name: CI

on:
  pull_request:
    branches: [ pre-release, release, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout sticky's cartridge
      uses: actions/checkout@v3
      with:
        path: link_stickyio_preview
    - name: Checkout SFRA
      uses: actions/checkout@v3
      with:
        repository: stickyio/storefront-reference-architecture
        ref: 'v5.3.0'
        ssh-key: ${{ secrets.SFRA_REPO_KEY }}
        path: storefront-reference-architecture
    - name: Copy base cartridges from SFRA to link_stickyio_preview
      run: cp -a storefront-reference-architecture/cartridges/. link_stickyio_preview/cartridges
    - name: Install Node.js 11.15
      uses: actions/setup-node@v2
      with:
        node-version: 11.15
    - run: ls link_stickyio_preview/cartridges
    - name: Set working dir to link_stickyio_preview
      run: cd link_stickyio_preview
    - name: Install link_stickyio_preview dependencies
      run: npm install
    - name: ls
    - name: Run unit tests
    - run: npm run test:unit
