# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ pre-release, release, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.15]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Checkout SFRA
      uses: actions/checkout@v3
      with:
        repository: stickyio/storefront-reference-architecture
        ref: 'v5.3.0'
        ssh-key: ${{ secrets.SFRA_REPO_KEY }}
        path: './..'
    - run: ls ./..
    - run: npm test:unit
