name: CI-CD

on:
  pull_request:
    branches: [ pre-release, release ]
#    types:
#      - closed

env:
  SFCC_OAUTH_CLIENT_ID: ${{ secrets.SFCC_CLIENT_ID }}
  SFCC_OAUTH_CLIENT_SECRET: ${{ secrets.SFCC_CLIENT_SECRET }}

jobs:
  build-and-deploy:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Set ODS instance to deploy
      run: |
        if [[ ${{ github.base_ref }} == pre-release ]]; then
          echo "SFCC_ODS_INSTANCE=002" >> $GITHUB_ENV
        else
          echo "SFCC_ODS_INSTANCE=003" >> $GITHUB_ENV
        fi
    - name: Checkout sticky's cartridge
      uses: actions/checkout@v3
      with:
        path: link_stickyio_preview
    - name: Checkout SFRA
      uses: actions/checkout@v3
      with:
        repository: stickyio/storefront-reference-architecture
        ref: 'v5.3.0'
        ssh-key: ${{ secrets.SFRA_REPO_KEY }}
        path: storefront-reference-architecture
    - name: Install Node.js 11.15
      uses: actions/setup-node@v2
      with:
        node-version: 11.15
    - name: Install storefront-reference-architecture dependencies
      run: npm install
      working-directory: ./storefront-reference-architecture
    - name: Compiling storefront-reference-architecture assets
      run: |
        npm run compile:js
        npm run compile:scss
        npm run compile:fonts
      working-directory: ./storefront-reference-architecture
    - name: Copy base cartridges from SFRA to link_stickyio_preview
      run: cp -a storefront-reference-architecture/cartridges/. link_stickyio_preview/cartridges
    - name: Install link_stickyio_preview dependencies
      run: npm install
      working-directory: ./link_stickyio_preview
    - name: Compiling link_stickyio_preview assets
      run: |
        npm run compile:js
        npm run compile:scss
      working-directory: ./link_stickyio_preview
    - name: Run unit tests
      run: npm run test:unit
      working-directory: ./link_stickyio_preview
#    - name: Run integration tests
#      run: npm run test:integration
#      working-directory: ./link_stickyio_preview
    - name: Install sfcc-ci
      run: npm install -g sfcc-ci
    - name: Auth sfcc-ci
      run: sfcc-ci client:auth
    - name: Creating folder for deploy
      run: cp -a link_stickyio_preview/cartridges/. ${{ github.run_id }}
    - name: Compress folder for deploy
      run: zip -r ${{ github.run_id }}.zip ${{ github.run_id }}
    - name: Deploy ${{ github.run_id }}.zip to SFCC ODS
      run: sfcc-ci code:deploy ${{ github.run_id }}.zip -i zzvg-${{ env.SFCC_ODS_INSTANCE }}.sandbox.us01.dx.commercecloud.salesforce.com
