name: Tests

on:
  pull_request:
    branches: [ pre-release, release ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sticky's cartridge
        uses: actions/checkout@v3
        with:
          path: link_stickyio_preview
      - name: Checkout SFRA
        uses: actions/checkout@v3
        with:
          repository: stickyio/storefront-reference-architecture
          ref: 'v5.3.0'
          ssh-key: ${{ secrets.SFRA_REPO_KEY }}
          path: storefront-reference-architecture
      - name: Install Node.js 11.15
        uses: actions/setup-node@v2
        with:
          node-version: 11.15
      - name: Install storefront-reference-architecture dependencies
        run: npm install
        working-directory: ./storefront-reference-architecture
      - name: Compiling storefront-reference-architecture assets
        run: |
          npm run compile:js
          npm run compile:scss
          npm run compile:fonts
        working-directory: ./storefront-reference-architecture
      - name: Copy base cartridges from SFRA to link_stickyio_preview
        run: cp -a storefront-reference-architecture/cartridges/. link_stickyio_preview/cartridges
      - name: Install link_stickyio_preview dependencies
        run: npm install
        working-directory: ./link_stickyio_preview
      - name: Compiling link_stickyio_preview assets
        run: |
          npm run compile:js
          npm run compile:scss
        working-directory: ./link_stickyio_preview
      - name: Run unit tests
        run: npm run test:unit
        working-directory: ./link_stickyio_preview
      #    - name: Run integration tests
      #      run: npm run test:integration
      #      working-directory: ./link_stickyio_preview
